CREATE SCHEMA IF NOT EXISTS db_catalog;
CREATE SCHEMA IF NOT EXISTS db_inventory;
CREATE SCHEMA IF NOT EXISTS db_orders;
CREATE SCHEMA IF NOT EXISTS db_payments_history;
CREATE SCHEMA IF NOT EXISTS db_users;